<a href="https://colab.research.google.com/github/Noahbisht0/Deep-Learning/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np 
a = np.array([[1,2,3,4,5,6],[2,3,4,6,8,9]], dtype = 'int64')
print(a)
a.ndim
a.shape
b = np.array([5,6,7,8])
b.ndim
a.dtype
a.itemsize
#nbytes = a.size * a.itemsize
a.nbytes



[[1 2 3 4 5 6]
 [2 3 4 6 8 9]]


96

In [ ]:
a[0,:]
a[:,2]
a[0,-1]
#[startindex:endindex:stepsize]
a[0,0:-1:2]
a[0,0] = 100
a
a[:,2] = [10,19]
a[1,:] = 9
a


array([[100,   2,  10,   4,   5,   6],
       [  9,   9,   9,   9,   9,   9]])

In [ ]:
d = np.array([[[1,2,3,4],[4,5,6,7]],[[8,9,10,11],[12,13,14,15]]])
d.ndim
print(d)

[[[ 1  2  3  4]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]]


In [ ]:
d[0,1,0] = 44
d
print(d[:,0,:])
print(d[:,1,:])
d[:,0,:] = [[99,999,9999,99999],[44,444,4444,44444]]
d

[[   99   999  9999 99999]
 [   44   444  4444 44444]]
[[44  5  6  7]
 [12 13 14 15]]


array([[[   99,   999,  9999, 99999],
        [   44,     5,     6,     7]],

       [[   44,   444,  4444, 44444],
        [   12,    13,    14,    15]]])

In [ ]:
np.zeros((2,2,3))
np.ones((2,2))
np.full((2,2),1000000)
np.full_like(a,9)


array([[9, 9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9, 9]])

In [ ]:
np.random.rand(3,4)

array([[0.30507326, 0.52987378, 0.55113808, 0.93318253],
       [0.08249144, 0.24597025, 0.03755502, 0.25429232],
       [0.33448203, 0.2756149 , 0.96794267, 0.59872591]])

In [ ]:
np.random.random_sample(a.shape)

array([[0.4016794 , 0.32426527, 0.86098651, 0.05465645, 0.88706739,
        0.32665005],
       [0.74389262, 0.28683435, 0.38814657, 0.99706746, 0.23349429,
        0.70015265]])

In [ ]:
np.random.randint(9)

8

In [ ]:
np.random.randint(1,3,size=(2,3))

array([[1, 1, 1],
       [2, 1, 1]])

In [ ]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
arr = np.array([1,2,3,4,5])
np.repeat(arr ,2,axis = 0)
b = np.copy(arr)
b[0] = 100000
b 
arr


array([1, 2, 3, 4, 5])

In [ ]:
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
         0.96017029],
       [-0.41614684, -0.9899925 , -0.65364362,  0.96017029, -0.14550003,
        -0.91113026]])

In [ ]:
z1 = np.ones((2,3))
z2 = np.full((3,2),5)
np.matmul(z1,z2)



array([[15., 15.],
       [15., 15.]])

In [ ]:
v = np.identity(3)
np.linalg.det(v)

1.0

In [ ]:
t = np.array([[1,2,3],[4,5,6]])
np.max(t)
np.min(t)
np.sum(t,axis = 0)
np.sum(t,axis = 1)
print("before:",t)
t.reshape((3,2))


before: [[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack([v1,v2,v2])
np.hstack([v1,v2,v2])

array([1, 2, 3, 4, 5, 6, 4, 5, 6])

In [ ]:
filedata = np.genfromtxt("d.txt",delimiter=',')
filedata.astype('int32')
filedata[filedata > 5]
np.all(filedata >6)


False